// ** Auth
export const signInActionTypes = {
  REQUEST_ACTION: 'SIGNIN_REQUEST_ACTION',
  SUCCESS_ACTION: 'SIGNIN_SUCCESS_ACTION',
  FAILED_ACTION: 'SIGNIN_FAILED_ACTION',
  STORE_USERID_ACTION: 'STORE_USERID_ACTION',
  STORE_TOKEN_ACTION: 'STORE_TOKEN_ACTION',
  SESSION_EXPIRED_ACTION: 'SESSION_EXPIRED_ACTION',
  PACKAGE_EXPIRED_ACTION: 'PACKAGE_EXPIRED_ACTION',
};

export const userTypeActionTypes = {
  USER_TYPE_ACTION: 'USER_TYPE_ACTION',
};

export const userSaveTypes = {
  USER_SAVE_ACTION: 'USER_SAVE_ACTION',
};

export const signUpActionTypes = {
  REQUEST_ACTION: 'SIGN_UP_REQUEST_ACTION',
  SUCCESS_ACTION: 'SIGN_UP_SUCCESS_ACTION',
  FAILED_ACTION: 'SIGN_UP_FAILED_ACTION',
};

export const getCollageActionTypes = {
  REQUEST_ACTION: 'GET_COLLAGE_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_COLLAGE_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_COLLAGE_FAILED_ACTION',
};

export const verifyUserAccountActionTypes = {
  REQUEST_ACTION: 'VERIFY__USER_ACCOUNT_REQUEST_ACTION',
  SUCCESS_ACTION: 'VERIFY__USER_ACCOUNT_SUCCESS_ACTION',
  FAILED_ACTION: 'VERIFY__USER_ACCOUNT_FAILED_ACTION',
};

export const resendVerifyEmailActionTypes = {
  REQUEST_ACTION: 'RESEND_VERIFY_EMAIL_REQUEST_ACTION',
  SUCCESS_ACTION: 'RESEND_VERIFY_EMAIL_SUCCESS_ACTION',
  FAILED_ACTION: 'RESEND_VERIFY_EMAIL_FAILED_ACTION',
};

export const forgotPasswordActionTypes = {
  REQUEST_ACTION: 'FORGOT_REQUEST_ACTION',
  SUCCESS_ACTION: 'FORGOT_SUCCESS_ACTION',
  FAILED_ACTION: 'FORGOT_FAILED_ACTION',
};

export const changePasswordActionTypes = {
  REQUEST_ACTION: 'CHANGE_PASSWORD_REQUEST_ACTION',
  SUCCESS_ACTION: 'CHANGE_PASSWORD_SUCCESS_ACTION',
  FAILED_ACTION: 'CHANGE_PASSWORD_FAILED_ACTION',
};
// ** profile
export const updatePasswordActionTypes = {
  REQUEST_ACTION: 'UPDATE_PASSWORD_REQUEST_ACTION',
  SUCCESS_ACTION: 'UPDATE_PASSWORD_SUCCESS_ACTION',
  FAILED_ACTION: 'UPDATE_PASSWORD_FAILED_ACTION',
};

export const updateProfileActionTypes = {
  REQUEST_ACTION: 'UPDATE_PROFILE_REQUEST_ACTION',
  SUCCESS_ACTION: 'UPDATE_PROFILE_SUCCESS_ACTION',
  FAILED_ACTION: 'UPDATE_PROFILE_FAILED_ACTION',
};

export const getProfileDataActionTypes = {
  REQUEST_ACTION: 'GET_PROFILE_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_PROFILE_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_PROFILE_FAILED_ACTION',
};

// ** report
export const studentWalletActionTypes = {
  REQUEST_ACTION: 'STUDENT_WALLET_REQUEST_ACTION',
  SUCCESS_ACTION: 'STUDENT_WALLET_SUCCESS_ACTION',
  FAILED_ACTION: 'STUDENT_WALLET_FAILED_ACTION',
};

export const studentExpensesActionTypes = {
  REQUEST_ACTION: 'STUDENT_EXPENSES_REQUEST_ACTION',
  SUCCESS_ACTION: 'STUDENT_EXPENSES_SUCCESS_ACTION',
  FAILED_ACTION: 'STUDENT_EXPENSES_FAILED_ACTION',
};

export const merchantIncomeActionTypes = {
  REQUEST_ACTION: 'MERCHANT_INCOME_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_INCOME_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_INCOME_FAILED_ACTION',
};

export const merchantWithdrawActionTypes = {
  REQUEST_ACTION: 'MERCHANT_WITHDRAW_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_WITHDRAW_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_WITHDRAW_FAILED_ACTION',
};

// ** payment
export const refreshCoinsActionTypes = {
  REQUEST_ACTION: 'STUDENT_REFRESH_COINS_REQUEST_ACTION',
  SUCCESS_ACTION: 'STUDENT_REFRESH_COINS_SUCCESS_ACTION',
  FAILED_ACTION: 'STUDENT_REFRESH_COINS_FAILED_ACTION',
};

export const addNewPaymentActionTypes = {
  REQUEST_ACTION: 'ADD_NEW_PAYMENT_REQUEST_ACTION',
  SUCCESS_ACTION: 'ADD_NEW_PAYMENT_SUCCESS_ACTION',
  FAILED_ACTION: 'ADD_NEW_PAYMENT_FAILED_ACTION',
};

export const chargeFromUserActionTypes = {
  // qr scan
  REQUEST_ACTION: 'CHARGE_FROM_USER_REQUEST_ACTION',
  SUCCESS_ACTION: 'CHARGE_FROM_USER_SUCCESS_ACTION',
  FAILED_ACTION: 'CHARGE_FROM_USER_FAILED_ACTION',
};

//merchant coin request
export const merchantCoinRequestActionTypes = {
  REQUEST_ACTION: 'MERCHANT_COIN_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_COIN_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_COIN_FAILED_ACTION',
};

//merchant coin request save
export const merchantCoinRequestSaveActionTypes = {
  REQUEST_ACTION: 'MERCHANT_COIN_REQUEST_SAVE_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_COIN_REQUEST_SAVE_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_COIN_REQUEST_SAVE_FAILED_ACTION',
};

//merchant coin request status check
export const findCoinStatusActionTypes = {
  REQUEST_ACTION: 'FIND_COIN_STATUS_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_COIN_STATUS_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_COIN_STATUS_FAILED_ACTION',
};

//user coin transfer to merchant
export const merchantCoinTransferActionTypes = {
  REQUEST_ACTION: 'MERCHANT_COIN_TRANSFER_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_COIN_TRANSFER_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_COIN_TRANSFER_FAILED_ACTION',
};

//user coin transfer to merchant cancle
export const merchantCoinTransferRejectActionTypes = {
  REQUEST_ACTION: 'MERCHANT_COIN_TRANSFER_REJECT_REQUEST_ACTION',
  SUCCESS_ACTION: 'MERCHANT_COIN_TRANSFER_REJECT_SUCCESS_ACTION',
  FAILED_ACTION: 'MERCHANT_COIN_TRANSFER_REJECT_FAILED_ACTION',
};

//merchant coin request cancel notify
export const coinRequestCancelNotifyActionTypes = {
  REQUEST_ACTION: 'COIN_REQUEST_CANCEL_NOTIFY_REQUEST_ACTION',
  SUCCESS_ACTION: 'COIN_REQUEST_CANCEL_NOTIFY_SUCCESS_ACTION',
  FAILED_ACTION: 'COIN_REQUEST_CANCEL_NOTIFY_FAILED_ACTION',
};

//merchant save store item
export const storeItemSaveActionTypes = {
  REQUEST_ACTION: 'STORE_ITEM_SAVE_REQUEST_ACTION',
  SUCCESS_ACTION: 'STORE_ITEM_SAVE_SUCCESS_ACTION',
  FAILED_ACTION: 'STORE_ITEM_SAVE_FAILED_ACTION',
};

export const withdrawCoinsActionTypes = {
  REQUEST_ACTION: 'WITHDRAW_COINS_REQUEST_ACTION',
  SUCCESS_ACTION: 'WITHDRAW_COINS_SUCCESS_ACTION',
  FAILED_ACTION: 'WITHDRAW_COINS_FAILED_ACTION',
};

//merchant get All items
export const getAllItemActionTypes = {
  REQUEST_ACTION: 'GET_ALL_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_ITEM_FAILED_ACTION',
};

//merchant find Item
export const findItemDataActionTypes = {
  REQUEST_ACTION: 'FIND_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_ITEM_FAILED_ACTION',
};

//merchant update Item
export const updateItemDataActionTypes = {
  REQUEST_ACTION: 'UPDATE_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'UPDATE_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'UPDATE_ITEM_FAILED_ACTION',
};

//qr update status
export const qrUpdateActionTypes = {
  REQUEST_ACTION: 'QR_UPDATE_STATUS_REQUEST_ACTION',
  SUCCESS_ACTION: 'QR_UPDATE_STATUS_SUCCESS_ACTION',
  FAILED_ACTION: 'QR_UPDATE_STATUS_FAILED_ACTION',
};

//qr validate
export const qrValidateActionTypes = {
  REQUEST_ACTION: 'QR_VALIDATE_REQUEST_ACTION',
  SUCCESS_ACTION: 'QR_VALIDATE_SUCCESS_ACTION',
  FAILED_ACTION: 'QR_VALIDATE_FAILED_ACTION',
};

//merchant delete Item
export const deleteItemDataActionTypes = {
  REQUEST_ACTION: 'DELETE_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'DELETE_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'DELETE_ITEM_FAILED_ACTION',
};

//student load all shops
export const getAllShopDataActionTypes = {
  REQUEST_ACTION: 'GET_ALL_SHOP_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_SHOP_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_SHOP_FAILED_ACTION',
};

//student find shop data
export const findShopDataActionTypes = {
  REQUEST_ACTION: 'FIND_SHOP_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_SHOP_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_SHOP_FAILED_ACTION',
};

//get all available items
export const getAllAvailableItemsActionTypes = {
  REQUEST_ACTION: 'GET_ALL_AVAILABLE_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_AVAILABLE_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_AVAILABLE_ITEM_FAILED_ACTION',
};

//add to cart
export const addToCartActionTypes = {
  REQUEST_ACTION: 'ADD_TO_CART_REQUEST_ACTION',
  SUCCESS_ACTION: 'ADD_TO_CART_SUCCESS_ACTION',
  FAILED_ACTION: 'ADD_TO_CART_FAILED_ACTION',
};

//file uploader
export const fileUploadActionTypes = {
  REQUEST_ACTION: 'FILE_UPLOAD_REQUEST_ACTION',
  SUCCESS_ACTION: 'FILE_UPLOAD_SUCCESS_ACTION',
  FAILED_ACTION: 'FILE_UPLOAD_FAILED_ACTION',
};

//student place Order
export const placeOrderActionTypes = {
  REQUEST_ACTION: 'PLACE_ORDER_REQUEST_ACTION',
  SUCCESS_ACTION: 'PLACE_ORDER_SUCCESS_ACTION',
  FAILED_ACTION: 'PLACE_ORDER_FAILED_ACTION',
};

export const placeOrderStationaryActionTypes = {
  REQUEST_ACTION: 'PLACE_ORDER_STATIONARY_REQUEST_ACTION',
  SUCCESS_ACTION: 'PLACE_ORDER_STATIONARY_SUCCESS_ACTION',
  FAILED_ACTION: 'PLACE_ORDER_STATIONARY_FAILED_ACTION',
};

//mechant get all active orders
export const getAllActiveOrderActionTypes = {
  REQUEST_ACTION: 'GET_ALL_ACTIVE_ORDER_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_ACTIVE_ORDER_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_ACTIVE_ORDER_FAILED_ACTION',
};

//mechant get all active orders
export const getAllStoreActiveOrderActionTypes = {
  REQUEST_ACTION: 'GET_ALL_STORE_ACTIVE_ORDER_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_STORE_ACTIVE_ORDER_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_STORE_ACTIVE_ORDER_FAILED_ACTION',
};

export const getAllStoreStationaryActiveOrderActionTypes = {
  REQUEST_ACTION: 'GET_ALL_STORE_STATIONARY_ACTIVE_ORDER_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_STORE_STATIONARY_ACTIVE_ORDER_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_STORE_STATIONARY_ACTIVE_ORDER_FAILED_ACTION',
};

//mechant get all active orders details
export const findOrderDetailsActionTypes = {
  REQUEST_ACTION: 'FIND_ORDER_DETAILS_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_ORDER_DETAILS_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_ORDER_DETAILS_FAILED_ACTION',
};

//order payment Request save merchant
export const orderPaymentRequestActionTypes = {
  REQUEST_ACTION: 'ORDER_PAYMENT_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_PAYMENT_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_PAYMENT_FAILED_ACTION',
};

//order payment Request find User
export const FindOrderPaymentRequestUserActionTypes = {
  REQUEST_ACTION: 'FIND_ORDER_PAYMENT_USER_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_ORDER_PAYMENT_USER_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_ORDER_PAYMENT_USER_FAILED_ACTION',
};

//order payment Request Update[cancle/accept]
export const orderPaymentRequestUpdateActionTypes = {
  REQUEST_ACTION: 'ORDER_PAYMENT_UPDATE_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_PAYMENT_UPDATE_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_PAYMENT_UPDATE_FAILED_ACTION',
};

//order status update
export const orderStatusUpdateActionTypes = {
  REQUEST_ACTION: 'ORDER_STATUS_UPDATE_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_STATUS_UPDATE_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_STATUS_UPDATE_FAILED_ACTION',
};

//order payment Request Update[cancle]
export const orderPaymentRequestCancelActionTypes = {
  REQUEST_ACTION: 'ORDER_PAYMENT_CANCEL_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_PAYMENT_CANCEL_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_PAYMENT_CANCEL_FAILED_ACTION',
};

//order payment Request cancle notify merchant[cancle]
export const orderPaymentRequestCancelNotifyActionTypes = {
  REQUEST_ACTION: 'ORDER_PAYMENT_CANCEL_NOFIFY_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_PAYMENT_CANCEL_NOFIFY_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_PAYMENT_CANCEL_NOFIFY_FAILED_ACTION',
};

//find order payment Request status check Merchant
export const FindOrderPaymentRequestStatusMerchantActionTypes = {
  REQUEST_ACTION: 'FIND_ORDER_PAYMENT_STATUS_MERCHANT_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_ORDER_PAYMENT_STATUS_MERCHANT_SUCCESS_ACTION',
  // REJECT_ACTION: 'FIND_ORDER_PAYMENT_STATUS_MERCHANT_REJECT_ACTION',
  FAILED_ACTION: 'FIND_ORDER_PAYMENT_STATUS_MERCHANT_FAILED_ACTION',
};

//order payment charge process
export const orderPaymentChargeActionTypes = {
  REQUEST_ACTION: 'ORDER_PAYMENT_CHARGE_REQUEST_ACTION',
  SUCCESS_ACTION: 'ORDER_PAYMENT_CHARGE_SUCCESS_ACTION',
  FAILED_ACTION: 'ORDER_PAYMENT_CHARGE_FAILED_ACTION',
};

//payment charge Student
export const paymentChargeStudentActionTypes = {
  REQUEST_ACTION: 'PAYMENT_CHARGE_STUDENT_REQUEST_ACTION',
  SUCCESS_ACTION: 'PAYMENT_CHARGE_STUDENT_SUCCESS_ACTION',
  FAILED_ACTION: 'PAYMENT_CHARGE_STUDENT_FAILED_ACTION',
};

//user check
export const userCheckActionTypes = {
  REQUEST_ACTION: 'USER_CHECK_REQUEST_ACTION',
  SUCCESS_ACTION: 'USER_CHECK_SUCCESS_ACTION',
  FAILED_ACTION: 'USER_CHECK_FAILED_ACTION',
};

//user resetPin
export const userResetPinActionTypes = {
  REQUEST_ACTION: 'USER_RESET_PIN_REQUEST_ACTION',
  SUCCESS_ACTION: 'USER_RESET_PIN_SUCCESS_ACTION',
  FAILED_ACTION: 'USER_RESET_PIN_FAILED_ACTION',
};

//fcmToken Update
export const fcmTokenUpdateActionTypes = {
  REQUEST_ACTION: 'FCM_TOKEN_UPDATE_REQUEST_ACTION',
  SUCCESS_ACTION: 'FCM_TOKEN_UPDATE_SUCCESS_ACTION',
  FAILED_ACTION: 'FCM_TOKEN_UPDATE_FAILED_ACTION',
};

//find order store detail
export const findOrderStoreDetailActionTypes = {
  REQUEST_ACTION: 'FIND_ORDER_STORE_DETAIL_REQUEST_ACTION',
  SUCCESS_ACTION: 'FIND_ORDER_STORE_DETAIL_SUCCESS_ACTION',
  FAILED_ACTION: 'FIND_ORDER_STORE_DETAIL_FAILED_ACTION',
};

//merchant get All Stationary items
export const getAllStationaryItemActionTypes = {
  REQUEST_ACTION: 'GET_ALL_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_ITEM_FAILED_ACTION',
};

//customer get All Stationary items
export const getAllAvailableStationaryItemActionTypes = {
  REQUEST_ACTION: 'GET_ALL_AVAILABLE_STATIONARY_ITEM_REQUEST_ACTION',
  SUCCESS_ACTION: 'GET_ALL_AVAILABLE_STATIONARY_ITEM_SUCCESS_ACTION',
  FAILED_ACTION: 'GET_ALL_AVAILABLE_STATIONARY_ITEM_FAILED_ACTION',
};

export const resetfindOrderStoreDetailActionTypes = {
  RESET_ACTION: 'RESET_FIND_ORDER_STORE_DETAIL_ACTION',
};

export const resetAuthActionTypes = {
  RESET_ACTION: 'RESET_AUTH_ACTION',
};

export const resetPinActionTypes = {
  RESET_ACTION: 'RESET_PIN_ACTION',
};

export const resetUserCheckActionTypes = {
  RESET_ACTION: 'RESET_USER_CHECK_ACTION',
};

export const resetProfileActionTypes = {
  RESET_ACTION: 'RESET_PROFILE_ACTION',
};

export const resetReportActionTypes = {
  RESET_ACTION: 'RESET_REPORT_ACTION',
};
export const resetPaymentActionTypes = {
  RESET_ACTION: 'RESET_PAYMENT_ACTION',
};

export const resetItemSaveActionTypes = {
  RESET_ACTION: 'RESET_ITEM_SAVE_ACTION',
};

export const resetFindItemActionTypes = {
  RESET_ACTION: 'RESET_FIND_ITEM_ACTION',
};

export const resetUpdateItemActionTypes = {
  RESET_ACTION: 'RESET_UPDATE_ITEM_ACTION',
};

export const resetDeleteItemActionTypes = {
  RESET_ACTION: 'RESET_DELETE_ITEM_ACTION',
};

export const resetFindShopActionTypes = {
  RESET_ACTION: 'RESET_FIND_SHOP_ACTION',
};

export const resetCartActionTypes = {
  RESET_ACTION: 'RESET_CART_ACTION',
};

export const resetUploadSelectActionTypes = {
  RESET_ACTION: 'FILE_UPLOAD_SELECT_ACTION',
};

export const resetUploadActionTypes = {
  RESET_ACTION: 'FILE_UPLOAD_ACTION',
};

//update cart
export const updateCartItemQuantityTypes = {
  REQUEST_ACTION: 'UPDATE_CART_ITEM_QUANTITY_ACTION',
};

export const resetPlaceOrderActionTypes = {
  RESET_ACTION: 'RESET_PLACE_ORDER_ACTION',
};

export const resetPlaceOrderStationaryActionTypes = {
  RESET_ACTION: 'RESET_PLACE_ORDER_STATIONARY_ACTION',
};

export const resetfindOrderDetailsActionTypes = {
  RESET_ACTION: 'RESET_FIND_ORDER_DETAILS_ACTION',
};

export const resetFindOrderPaymentRequestUserActionTypes = {
  RESET_ACTION: 'RESET_FIND_ORDER_PAYMENT_DETAILS_ACTION',
};

export const resetorderPaymentRequestMerchantActionTypes = {
  RESET_ACTION: 'RESET_ORDER_PAYMENT_REQUEST_ACTION',
};

export const resetFindOrderPaymentRequestStatusMerchantActionTypes = {
  RESET_ACTION: 'RESET_FIND_ORDER_PAYMENT_STATUS_MERCHANT_ACTION',
};

export const resetOrderPaymentChargeActionTypes = {
  RESET_ACTION: 'RESET_ORDER_PAYMENT_CHARGE_ACTION',
};

export const resetQrValidateActionTypes = {
  RESET_ACTION: 'RESET_QR_VALIDATE_ACTION',
};

export const resetOrderPaymentRequestCancelNotifyActionTypes = {
  RESET_ACTION: 'RESET_ORDER_PAYMENT_REQUEST_NOTIFIY_ACTION',
};

export const resetOrderPaymentRequestCancelActionTypes = {
  RESET_ACTION: 'RESET_ORDER_PAYMENT_REQUEST_CANCEL_ACTION',
};

export const resetOrderPaymentRequestAcceptActionTypes = {
  RESET_ACTION: 'RESET_ORDER_PAYMENT_REQUEST_ACCEPT_CANCEL_ACTION',
};

export const RESET_ORDER_TYPE = 'RESET_ORDER_TYPE';

export const RESET_ITEM_TYPE = 'RESET_ITEM_TYPE';

export const resetPaymentChargeStudentActionTypes = {
  RESET_ACTION: 'RESET_PAYMENT_CHARGE_STUDENT_ACTION',
};
//-------------------stationary---
export const resetStationaryItemSaveActionTypes = {
  RESET_ACTION: 'RESET_ITEM_SAVE_ACTION',
};

export const resetStationaryFindItemActionTypes = {
  RESET_ACTION: 'RESET_FIND_ITEM_ACTION',
};

export const resetUpdateStationaryItemActionTypes = {
  RESET_ACTION: 'RESET_UPDATE_ITEM_ACTION',
};

export const resetDeleteStationaryItemActionTypes = {
  RESET_ACTION: 'RESET_DELETE_ITEM_ACTION',
};
